version: '3.9'
services:
  stack_database:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD
      - POSTGRES_USER
      - POSTGRES_DB
    ports:
      - 5433:5433
  backend:
    build: .
    command: yarn start:dev
    ports:
      - 4000:4000
    environment:
      - DATABASE_URL
      - PORT
    volumes:
      - .:/app/
      - nodemodules:/app/node_modules
    links:
      - stack_database
    depends_on:
      - stack_database

volumes:
  nodemodules: {}