version: '3.9'
services:
  stack_database:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: Stack
      POSTGRES_PASSWORD: stack
      POSTGRES_DB: stack
    ports:
      - 5432:5432
#   backend:
#     build: .
#     command: yarn start:dev
#     ports:
#       - 4000:4000
#     environment:
#       - DATABASE_URL
#       - PORT
#     volumes:
#       - .:/app/
#       - nodemodules:/app/node_modules
#     links:
#       - database
#     depends_on:
#       - database

# volumes:
#   nodemodules: {}
