name: PR checks

on:
  pull_request:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: 'backend: yarn install'
        run: yarn --prefer-offline --frozen-lockfile
      - name: 'backend: lint'
        run: yarn lint
      # - name: 'backend: test'
      #   run: yarn test
      - name: 'backend: build'
        run: CI=false yarn build